services:
  backend:
    build: .

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
